### PR TITLE
Made some changes to allow for easier customization via subclassing. 

### PR DESCRIPTION
**Pull request by vtagle**
Hello, 

I like what you've done with MNCalendarView and I'm using it in a project I'm currently working on. There's a couple things with the way the code was set up, though, that prevented me from customizing it for my project so I've made some minor changes.

### CODE REVIEW

**Comment by min** [comment]
Is there anything particular you wanted to customize? I was hoping you can accomplish most customizations by subclassing MNCalendarViewDayCell/MNCalendarViewWeekdayCell and registering you class to the MNCalendarView instance.

**Comment by vtagle** [comment]
Well, the issues I had were:
- The classes for MNCalendarViewDayCell and MNCalendarViewWeekdayCell are registered in the initWithFrame method when the getter for collectionView is called so if I assign them after the MNCalendarView is created, the MNCalendarView never registers them with it's UICollectionView instance. 
- My MNCalendarViewDayCell subclass needs to pull data from an external source to display on the calendar. The UICollectionView instance handles creation of it's cells so in order for me to do what I want, I needed to override collectionView:cellForItemAtIndexPath: I could've also used a class method to set a static pointer to either a block or a delegate but that just seemed really messy. Also, according to the UICollectionViewCell documentation, the collection view is supposed to handle presentation of the cells it instantiates which is why I needed to subclass MNCalendarView. 
- initWithCoder was never defined so if I set up a UIView and changed it to a MNCalendarView instance, it wouldn't get initialized properly. 

Vince

**Comment by min** [comment]
gotcha, makes sense. i'll make it easier to register custom cells and provide some more documentation around it. in the meantime, your PR looks good. thanks for the contribution!

**Comment by vtagle** [comment]
No, thank you for writing the class. It's saved me a bunch of time and trouble :)

**Pull request merged**
